### ISSUE TITLE
LocaleSwitch documentation

### ISSUE THREAD

**Issue by lochstar** [CherrySoftware/react-translate-maker#3]
I'm trying to use the LocaleSwitch component.

It renders correctly and updates the new language at `this.context.translate`, but the component renders with the first select option selected, no matter which option is chosen.

The strings do not update until navigating back to the page or a refresh is forced. I can make this happen by using an `onChange` handler and calling `this.forceUpdate()`

Is this the recommended way to handle a locale change?

**Comment by seeden** [comment]
This component has a property named setLocale (Boolean).
The default value was set to false. I think that users are expecting immediate change. I am going to change the default value to true.

**Comment by seeden** [comment]
Default value of the property setLocale is true in the latest version 0.0.32. I have added documentation too https://github.com/CherrySoftware/react-translate-maker#locale-switch with small roadmap for this component in short run https://github.com/CherrySoftware/react-translate-maker#roadmap

Let me know if it is working for you

**Comment by lochstar** [comment]
Thanks, I noticed the setLocale option, but it seems like the context change isn't triggering a re-render. I thought it may have something to do with this [existing limitation](https://facebook.github.io/react/docs/context.html#known-limitations).

**Comment by seeden** [comment]
Yes you are right. I will fix it tomorrow and I will add a test too.

**Comment by seeden** [comment]
I have updated components LocaleSwitch and LocaleProvider. More information you can find in the [documentation](https://github.com/CherrySoftware/react-translate-maker#locale-switch). I rewrote tests too. It is working correctly. You are able to use LocaleSwitch with LocaleProvider in the two modes: controlled and uncontrolled. It is up to you. Let me know what do you think. I am closing it because it is working
